export const REQUEST_AUTHENTICATE_USER = 'REQUEST_AUTHENTICATE_USER';
export const RECEIVE_AUTHENTICATE_USER = 'RECEIVE_AUTHENTICATE_USER';
export const REQUEST_REGISTER_USER = 'REQUEST_AUTHENTICATE_USER';
export const RECEIVE_REGISTER_USER = 'RECEIVE_REGISTER_USER';
