export const REQUEST_ALL_ORDERS = 'REQUEST_ALL_ORDERS';
export const RECEIVE_ALL_ORDERS = 'RECEIVE_ALL_ORDERS';
export const REQUEST_ADD_ORDER = 'REQUEST_ALL_ORDER';
export const RECEIVE_ADD_ORDER = 'REQUEST_ADD_ORDER';
export const REQUEST_DELETE_ORDER = 'REQUEST_DELETE_ORDER';
export const RECEIVE_DELETE_ORDER = 'RECEIVE_DELETE_ORDER';
export const REQUEST_EDIT_ORDER = 'REQUEST_DELETE_ORDER';
export const RECEIVE_EDIT_ORDER = 'RECEIVE_EDIT_ORDER';
